# Generated by Django 5.2.7 on 2025-10-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_loan_outstanding_principal_loan_total_interest_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid_off_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
